version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - echo "Build completed successfully, no tests to run."

  post_build:
    commands:
      - echo "Build and installation steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
