version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - pytest  # Run your tests (optional)
artifacts:
  files:
    - '**/*'
  discard-paths: yes
