-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 13:51:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizza_db` ;

-- -----------------------------------------------------
-- Table `pizza_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_db`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  `password` VARCHAR(80) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_db`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_db`.`pizzas` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `cheese` VARCHAR(45) NOT NULL,
  `pepperoni` VARCHAR(45) NOT NULL,
  `supreme` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(100) NOT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  `updated_at` DATE NULL DEFAULT NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_pizza`),
  INDEX `fk_pizzas_users_idx` (`users_id_users` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_users`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `pizza_db`.`users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
